version: "3.3"

services:
    nginx:
        build:
            context: .
            dockerfile: docker/Nginx.Dockerfile
        ports:
            - 8098:80
        volumes:
            - ./:/var/www/laravel-docker
        links:
            - fpm
    fpm:
        build:
            context: .
            dockerfile: docker/Fpm.Dockerfile
        volumes:
            - ./:/var/www/laravel-docker
        links:
            - mysql
    mysql:
        image: mysql:5.7
        ports:
            - 33061:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=requests-api-demo
